version: "3.8"

services:
  mongo:
    image: mongo:7.0
    container_name: scramble-mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_ROOT_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./docker/development/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - scramble-network

  redis:
    image: redis:7.2-alpine
    container_name: scramble-redis
    restart: unless-stopped
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - scramble-network

  backend:
    build:
      context: .
      dockerfile: ./apps/backend/Dockerfile.dev
    container_name: scramble-backend
    restart: unless-stopped
    environment:
      - NODE_ENV=development
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./apps/backend:/app
      - /app/node_modules
    depends_on:
      - mongo
      - redis
    networks:
      - scramble-network

volumes:
  mongo_data:
  redis_data:

networks:
  scramble-network:
    driver: bridge
